### PR TITLE
official_devices: Drop RMX1941

### PR DESCRIPTION
**Pull request by ok-ano0s**

### CODE REVIEW

**Review by whyredfire — COMMENTED** [review]
https://en.wikipedia.org/wiki/April_Fools%27_Day

**Comment by bheatleyyy** [comment]
@ok-ano0s LMAOOOO

**Comment by geek0609** [comment]
@ok-ano0s BRUH

**Comment by ok-ano0s** [comment]
Bruh u gays told me I am kicked and now playing with it or something? Bruh :|

**Pull request closed without merging**
